cli: add a way to control the output stream
reanahub/reana-client-go pull request #41
Opened 2022-07-20 15:10 UTC by BrunoRosendo

closes #24

The strategy was:
- Change the Cobra's output to `os.Stdout`, since it uses `Stderr` by default. This only needed to be done at the root command
- In every command, change the `fmt` commands to `cmd` (e.g. `cmd.PrintLn()`)
- In `utils` or other functions without accces to `cmd`, pass the output through a parameter and use it

2022-07-21 16:06 UTC, BrunoRosendo commented
Converted to draft because I think it's better to implement this here, in the utils functions: https://github.com/reanahub/reana-client-go/pull/39#discussion_r926683191

2022-07-22 16:05 UTC, BrunoRosendo commented
Review after #47

2022-07-26 12:44 UTC, mdonadoni requested changes
Works well! However the `open` and `close` commands are still using `fmt.Print*`. Could you please update the PR to also include the changes to those commands?

2022-07-26 13:37 UTC, mdonadoni approved these changes
Nice job!

2022-07-26 13:38 UTC, merged